AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: s3://lambda-artifacts-fdf0e1808c7d988e/2efcc4029ee5aa25b6fbd387fe03ad57
      Description: Call the AWS Lambda API
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      Tracing: Active
      Layers:
      - Ref: libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: whooper-lib
      Description: Dependencies for the whooper sample app.
      ContentUri: s3://lambda-artifacts-fdf0e1808c7d988e/0bb183001cc4465892c1da9928281f89
      CompatibleRuntimes:
      - python3.8
